### ISSUE TITLE
Android: A lot of broken areas 

### ISSUE THREAD

**Issue by onreego** [primergrey/minimallyinvasivebrainandspine.com#17]
![10720967_883532157784_2044669794_n](https://cloud.githubusercontent.com/assets/4663425/6258004/85ceb870-b78a-11e4-92db-0f3fe2ac6ead.jpg)
![10997182_883532092914_725318368_n](https://cloud.githubusercontent.com/assets/4663425/6258005/85d0426c-b78a-11e4-9461-1e3ca8f67912.jpg)
![11004687_883532142814_960720769_n](https://cloud.githubusercontent.com/assets/4663425/6258007/85d0fbc6-b78a-11e4-83f7-6340acc6b3cd.jpg)
![11004786_883532147804_2018865601_n](https://cloud.githubusercontent.com/assets/4663425/6258006/85d0fa36-b78a-11e4-89b2-72f49aa35e4a.jpg)

**Comment by fxchain** [comment]
should look much better now
