### ISSUE TITLE
Schedule a Consultation button disappears when I roll over "spine" in procedures or any of the testimonials, on purpose?

### ISSUE THREAD

**Issue by plumpgiraffe** [primergrey/minimallyinvasivebrainandspine.com#27]

**Comment by fxchain** [comment]
because if you rollover Spine, the button stays in front of the content. Same for testimonials. What could we do, any ideas?
![minimally invasive brain and spine - mozilla firefox_032](https://cloud.githubusercontent.com/assets/779967/6383300/2b260e42-bd15-11e4-833b-ea0a99193fef.png)

**Comment by plumpgiraffe** [comment]
Was that done on purpose?

RACHELFLORES
DESIGNER

713 401 2835
2119 Dallas St, Unit C, Houston, TX 77003

Twitter: @pgteam
LinkedIn: linkedin.com/in/rachelflores

**Comment by fxchain** [comment]
fixed now
