### ISSUE TITLE
MAC: CHROME: "Schedule a consultation" bubble doesn't want to leave the party.

### ISSUE THREAD

**Issue by hannyleece** [primergrey/minimallyinvasivebrainandspine.com#28]
pop up for "refer a patient" gets stuck behind the "schedule a consultation" bubble.
![form pop up](https://cloud.githubusercontent.com/assets/8961322/6258335/5ff4eb80-b78d-11e4-8122-cfa798585dda.png)

**Comment by fxchain** [comment]
fixed
