### ISSUE TITLE
Android: The first view looks like a button

### ISSUE THREAD

**Issue by onreego** [primergrey/minimallyinvasivebrainandspine.com#4]

**Comment by fxchain** [comment]
So what??

**Comment by plumpgiraffe** [comment]
Removed shadow, added a little transparency. this should alleviate that issue.

RACHELFLORES
DESIGNER

713 401 2835
2119 Dallas St, Unit C, Houston, TX 77003

Twitter: @pgteam
LinkedIn: linkedin.com/in/rachelflores
