### ISSUE TITLE
Android: Schedule a consultation is kind of wonky

### ISSUE THREAD

**Issue by onreego** [primergrey/minimallyinvasivebrainandspine.com#8]
Maybe this button changes on mobile?

**Comment by plumpgiraffe** [comment]
Maybe we can just nix that all together in mobile? @thewhether

**Comment by thewhether** [comment]
I dont think that's nixable

On Wed, Feb 18, 2015 at 4:55 PM, plumpgiraffe notifications@github.com
wrote:

> Maybe we can just nix that all together in mobile? @thewhether
> https://github.com/thewhether
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/primergrey/minimallyinvasivebrainandspine.com/issues/8#issuecomment-74966433
> .

## 

_CHRIS_VALDEZ
STRATEGY & CREATIVE DIRECTION

O. 713 401 2835
Twitter @pgteam http://twitter.com/pgteam
Facebook /startwithgrey http://facebook.com/startwithgrey
LinkedIn /chrisivaldez http://linkedin.com/in/chrisivaldez

_PLEASE NOTE_:\* I will be out of the office on Friday, February 20 and
Friday, February 27. Thanks in advance for your help in planning ahead.*

**Comment by plumpgiraffe** [comment]
can we have it as a sticky footer instead of that flag?

**Comment by thewhether** [comment]
I think so.

On Wed, Feb 18, 2015 at 4:57 PM, plumpgiraffe notifications@github.com
wrote:

> can we have it as a sticky footer instead of that flag?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/primergrey/minimallyinvasivebrainandspine.com/issues/8#issuecomment-74966776
> .

## 

_CHRIS_VALDEZ
STRATEGY & CREATIVE DIRECTION

O. 713 401 2835
Twitter @pgteam http://twitter.com/pgteam
Facebook /startwithgrey http://facebook.com/startwithgrey
LinkedIn /chrisivaldez http://linkedin.com/in/chrisivaldez

_PLEASE NOTE_:\* I will be out of the office on Friday, February 20 and
Friday, February 27. Thanks in advance for your help in planning ahead.*

**Comment by plumpgiraffe** [comment]
Cool. @fxchain , can you change that to a white sticky footer in mobile? Same type. Let me know if you need me to mock it up.
